<a href="https://colab.research.google.com/github/DineshY1011/US_Accident/blob/main/Milestone_2/Week_4/Day_20/Final_Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('/content/drive/MyDrive/US_Dataset/US_Accidents_sampled_1M.csv')
df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-7182628,Source1,1,2020-04-17 09:29:30,2020-04-17 10:29:30,26.706900,-80.119360,26.706900,-80.119360,0.000,...,False,False,False,False,True,False,Day,Day,Day,Day
1,A-5404588,Source1,2,2022-04-21 10:01:00.000000000,2022-04-21 11:44:08.000000000,38.781024,-121.265820,38.780377,-121.265815,0.045,...,False,False,True,False,False,False,Day,Day,Day,Day
2,A-156000,Source3,3,2016-08-12 16:45:00,2016-08-12 17:15:00,33.985249,-84.269348,NaN,NaN,0.000,...,False,False,False,False,False,False,Day,Day,Day,Day
3,A-1871277,Source2,3,2019-09-20 15:22:16,2019-09-20 15:56:00,47.118706,-122.556908,NaN,NaN,0.000,...,False,False,False,False,False,False,Day,Day,Day,Day
4,A-2031222,Source2,2,2019-06-03 16:55:43,2019-06-03 18:12:09,33.451355,-111.890343,NaN,NaN,0.000,...,False,False,False,False,False,False,Day,Day,Day,Day

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 46 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   ID                     1000000 non-null  object
 1   Source                 1000000 non-null  object
 2   Severity               1000000 non-null  int64
 3   Start_Time             1000000 non-null  object
 4   End_Time               1000000 non-null  object
 5   Start_Lat              1000000 non-null  float64
 6   Start_Lng              1000000 non-null  float64
 7   End_Lat                559358 non-null   float64
 8   End_Lng                559358 non-null   float64
 9   Distance(mi)           1000000 non-null  float64
 10  Description            999999 non-null   object
 11  Street                 998593 non-null   object
 12  City                   999964 non-null   object
 13  County                 1000000 non-null  object
 14  State                  1000000 non-null  object
 15  Zipcode                999755 non-null   object
 16  Country                1000000 non-null  object
 17  Timezone               999007 non-null   object
 18  Airport_Code           997099 non-null   object
 19  Weather_Timestamp      984422 non-null   object
 20  Temperature(F)         978811 non-null   float64
 21  Wind_Chill(F)          741085 non-null   float64
 22  Humidity(%)            977513 non-null   float64
 23  Pressure(in)           981780 non-null   float64
 24  Visibility(mi)         977075 non-null   float64
 25  Wind_Direction         977182 non-null   object
 26  Wind_Speed(mph)        925598 non-null   float64
 27  Precipitation(in)      714393 non-null   float64
 28  Weather_Condition      977560 non-null   object
 29  Amenity                1000000 non-null  bool
 30  Bump                   1000000 non-null  bool
 31  Crossing               1000000 non-null  bool
 32  Give_Way               1000000 non-null  bool
 33  Junction               1000000 non-null  bool
 34  No_Exit                1000000 non-null  bool
 35  Railway                1000000 non-null  bool
 36  Roundabout             1000000 non-null  bool
 37  Station                1000000 non-null  bool
 38  Stop                   1000000 non-null  bool
 39  Traffic_Calming        1000000 non-null  bool
 40  Traffic_Signal         1000000 non-null  bool
 41  Turning_Loop           1000000 non-null  bool
 42  Sunrise_Sunset         996913 non-null   object
 43  Civil_Twilight         996913 non-null   object
 44  Nautical_Twilight      996913 non-null   object
 45  Astronomical_Twilight  996913 non-null   object
dtypes: bool(13), float64(12), int64(1), object(20)
memory usage: 264.2+ MB

In [6]:
(df.isnull().sum() / df.shape[0])*100

ID                        0.0000
Source                    0.0000
Severity                  0.0000
Start_Time                0.0000
End_Time                  0.0000
Start_Lat                 0.0000
Start_Lng                 0.0000
End_Lat                  44.0642
End_Lng                  44.0642
Distance(mi)              0.0000
Description               0.0001
Street                    0.1407
City                      0.0036
County                    0.0000
State                     0.0000
Zipcode                   0.0245
Country                   0.0000
Timezone                  0.0993
Airport_Code              0.2901
Weather_Timestamp         1.5578
Temperature(F)            2.1189
Wind_Chill(F)            25.8915
Humidity(%)               2.2487
Pressure(in)              1.8220
Visibility(mi)            2.2925
Wind_Direction            2.2818
Wind_Speed(mph)           7.4402
Precipitation(in)        28.5607
Weather_Condition         2.2440
Amenity                   0.0000
Bump                      0.0000
Crossing                  0.0000
Give_Way                  0.0000
Junction                  0.0000
No_Exit                   0.0000
Railway                   0.0000
Roundabout                0.0000
Station                   0.0000
Stop                      0.0000
Traffic_Calming           0.0000
Traffic_Signal            0.0000
Turning_Loop              0.0000
Sunrise_Sunset            0.3087
Civil_Twilight            0.3087
Nautical_Twilight         0.3087
Astronomical_Twilight     0.3087
dtype: float64

In [7]:
# Drop the columns of 'End_Lat', 'End_Lng'
df = df.drop(columns=['End_Lat', 'End_Lng'])

In [8]:
# Convert the 'Start_Time' and 'End_Time' columns to datetime format
df['Start_Time'] = pd.to_datetime(df['Start_Time'], format='mixed')
df['End_Time'] = pd.to_datetime(df['End_Time'], format='mixed')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 44 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   ID                     1000000 non-null  object
 1   Source                 1000000 non-null  object
 2   Severity               1000000 non-null  int64
 3   Start_Time             1000000 non-null  datetime64[ns]
 4   End_Time               1000000 non-null  datetime64[ns]
 5   Start_Lat              1000000 non-null  float64
 6   Start_Lng              1000000 non-null  float64
 7   Distance(mi)           1000000 non-null  float64
 8   Description            999999 non-null   object
 9   Street                 998593 non-null   object
 10  City                   999964 non-null   object
 11  County                 1000000 non-null  object
 12  State                  1000000 non-null  object
 13  Zipcode                999755 non-null   object
 14  Country                1000000 non-null  object
 15  Timezone               999007 non-null   object
 16  Airport_Code           997099 non-null   object
 17  Weather_Timestamp      984422 non-null   object
 18  Temperature(F)         978811 non-null   float64
 19  Wind_Chill(F)          741085 non-null   float64
 20  Humidity(%)            977513 non-null   float64
 21  Pressure(in)           981780 non-null   float64
 22  Visibility(mi)         977075 non-null   float64
 23  Wind_Direction         977182 non-null   object
 24  Wind_Speed(mph)        925598 non-null   float64
 25  Precipitation(in)      714393 non-null   float64
 26  Weather_Condition      977560 non-null   object
 27  Amenity                1000000 non-null  bool
 28  Bump                   1000000 non-null  bool
 29  Crossing               1000000 non-null  bool
 30  Give_Way               1000000 non-null  bool
 31  Junction               1000000 non-null  bool
 32  No_Exit                1000000 non-null  bool
 33  Railway                1000000 non-null  bool
 34  Roundabout             1000000 non-null  bool
 35  Station                1000000 non-null  bool
 36  Stop                   1000000 non-null  bool
 37  Traffic_Calming        1000000 non-null  bool
 38  Traffic_Signal         1000000 non-null  bool
 39  Turning_Loop           1000000 non-null  bool
 40  Sunrise_Sunset         996913 non-null   object
 41  Civil_Twilight         996913 non-null   object
 42  Nautical_Twilight      996913 non-null   object
 43  Astronomical_Twilight  996913 non-null   object
dtypes: bool(13), datetime64[ns](2), float64(10), int64(1), object(18)
memory usage: 248.9+ MB

In [9]:
# Convert coordinates to numeric (if not already)
df['Start_Lat'] = pd.to_numeric(df['Start_Lat'], errors='coerce')
df['Start_Lng'] = pd.to_numeric(df['Start_Lng'], errors='coerce')

In [10]:
(df.isnull().sum() / df.shape[0])*100

ID                        0.0000
Source                    0.0000
Severity                  0.0000
Start_Time                0.0000
End_Time                  0.0000
Start_Lat                 0.0000
Start_Lng                 0.0000
Distance(mi)              0.0000
Description               0.0001
Street                    0.1407
City                      0.0036
County                    0.0000
State                     0.0000
Zipcode                   0.0245
Country                   0.0000
Timezone                  0.0993
Airport_Code              0.2901
Weather_Timestamp         1.5578
Temperature(F)            2.1189
Wind_Chill(F)            25.8915
Humidity(%)               2.2487
Pressure(in)              1.8220
Visibility(mi)            2.2925
Wind_Direction            2.2818
Wind_Speed(mph)           7.4402
Precipitation(in)        28.5607
Weather_Condition         2.2440
Amenity                   0.0000
Bump                      0.0000
Crossing                  0.0000
Give_Way                  0.0000
Junction                  0.0000
No_Exit                   0.0000
Railway                   0.0000
Roundabout                0.0000
Station                   0.0000
Stop                      0.0000
Traffic_Calming           0.0000
Traffic_Signal            0.0000
Turning_Loop              0.0000
Sunrise_Sunset            0.3087
Civil_Twilight            0.3087
Nautical_Twilight         0.3087
Astronomical_Twilight     0.3087
dtype: float64

In [11]:
# Drop the rows with missing values except some columns.
df = df.dropna(subset=['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'Distance(mi)', 'Description', 'Street', 'City', 'County',
       'State', 'Zipcode', 'Country', 'Timezone', 'Airport_Code',
       'Weather_Timestamp', 'Temperature(F)', 'Humidity(%)',
       'Pressure(in)', 'Visibility(mi)', 'Wind_Direction','Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'])

In [12]:
(df.isnull().sum() / df.shape[0])*100

ID                        0.000000
Source                    0.000000
Severity                  0.000000
Start_Time                0.000000
End_Time                  0.000000
Start_Lat                 0.000000
Start_Lng                 0.000000
Distance(mi)              0.000000
Description               0.000000
Street                    0.000000
City                      0.000000
County                    0.000000
State                     0.000000
Zipcode                   0.000000
Country                   0.000000
Timezone                  0.000000
Airport_Code              0.000000
Weather_Timestamp         0.000000
Temperature(F)            0.000000
Wind_Chill(F)            23.854236
Humidity(%)               0.000000
Pressure(in)              0.000000
Visibility(mi)            0.000000
Wind_Direction            0.000000
Wind_Speed(mph)           5.089997
Precipitation(in)        27.520515
Weather_Condition         0.000000
Amenity                   0.000000
Bump                      0.000000
Crossing                  0.000000
Give_Way                  0.000000
Junction                  0.000000
No_Exit                   0.000000
Railway                   0.000000
Roundabout                0.000000
Station                   0.000000
Stop                      0.000000
Traffic_Calming           0.000000
Traffic_Signal            0.000000
Turning_Loop              0.000000
Sunrise_Sunset            0.000000
Civil_Twilight            0.000000
Nautical_Twilight         0.000000
Astronomical_Twilight     0.000000
dtype: float64

In [13]:
df[['Wind_Chill(F)', 'Wind_Speed(mph)', 'Precipitation(in)']].sample(5)

        Wind_Chill(F)  Wind_Speed(mph)  Precipitation(in)
42974            44.0              5.0                0.0
970437           54.0              0.0                0.0
963558           23.0             21.0                0.0
516861           70.0              3.0                0.0
649130           31.0              0.0                0.0

In [14]:
(df[['Wind_Chill(F)', 'Wind_Speed(mph)', 'Precipitation(in)']].isnull().sum())/df.shape[0]*100

Wind_Chill(F)        23.854236
Wind_Speed(mph)       5.089997
Precipitation(in)    27.520515
dtype: float64

In [15]:
# Median imputation for Wind_Speed(mph)
wind_median = df['Wind_Speed(mph)'].median()
df['Wind_Speed(mph)'] = df['Wind_Speed(mph)'].fillna(wind_median)

# Primary imputation for Precipitation(in): zero-fill
df['Precipitation(in)'] = df['Precipitation(in)'].fillna(0.0)

# Secondary imputation for known rain days: fill remaining gaps with median of nonzero precipitation
median_nonzero_precip = df.loc[df['Precipitation(in)'] > 0, 'Precipitation(in)'].median()

# Example mask for known rain days (replace with your actual condition)
# e.g., df['Rain_Flag'] == 1 or based on another indicator column
rain_day_mask = df['Precipitation(in)'].isna()  # placeholder if original missing flags retained

# Apply secondary imputation
df.loc[rain_day_mask, 'Precipitation(in)'] = median_nonzero_precip

In [16]:
from sklearn.linear_model import LinearRegression

# Select features to predict Wind_Chill(F)
reg_features = ['Wind_Speed(mph)', 'Temperature(F)', 'Humidity(%)']  # adjust to available predictors

# Split known and unknown
known_wc = df[df['Wind_Chill(F)'].notna()]
unknown_wc = df[df['Wind_Chill(F)'].isna()]

# Train regression model
X_train = known_wc[reg_features]
y_train = known_wc['Wind_Chill(F)']
reg = LinearRegression()
reg.fit(X_train, y_train)

# Predict missing Wind_Chill(F)
X_pred = unknown_wc[reg_features]
predicted_wc = reg.predict(X_pred)

# Impute missing values
df.loc[df['Wind_Chill(F)'].isna(), 'Wind_Chill(F)'] = predicted_wc

In [17]:
(df[['Wind_Chill(F)', 'Wind_Speed(mph)', 'Precipitation(in)']].isnull().sum())/df.shape[0]*100

Wind_Chill(F)        0.0
Wind_Speed(mph)      0.0
Precipitation(in)    0.0
dtype: float64

In [18]:
# 1. Parse datetimes
df["Start_Time"] = pd.to_datetime(df["Start_Time"], errors="coerce")
df["End_Time"]   = pd.to_datetime(df["End_Time"], errors="coerce")

In [19]:
# 2. Drop duplicates and rows with invalid times
df = df.drop_duplicates(subset="ID")
df = df.dropna(subset=["Start_Time", "End_Time"])

In [20]:
# 3. Drop rows missing critical location data
df = df.dropna(subset=["Start_Lat", "Start_Lng"])

In [21]:
# 4. Compute incident duration in minutes
df["Duration_Minutes"] = (df["End_Time"] - df["Start_Time"]).dt.total_seconds() / 60

In [22]:
# 5. Extract temporal features
df["Hour"]        = df["Start_Time"].dt.hour
df["DayOfWeek"]   = df["Start_Time"].dt.weekday
df["Month"]       = df["Start_Time"].dt.month
df["IsWeekend"]   = df["DayOfWeek"].isin([5,6]).astype(int)

In [23]:
# 6. Encode boolean traffic feature flags as integers
bool_cols = [
    "Roundabout",
    "Station",
    "Stop",
    "Traffic_Calming",
    "Traffic_Signal",
    "Turning_Loop"
]
for col in bool_cols:
    df[col] = df[col].astype(int)

In [24]:
# 7. Encode light condition as binary day/night
df["IsDay"] = (df["Sunrise_Sunset"] == "Day").astype(int)

In [25]:
# 8. Drop columns not used for modeling
drop_cols = [
    "ID",
    "Source",
    "Description",
    "Street",
    "Start_Time",
    "End_Time",
    "Sunrise_Sunset",
    "Civil_Twilight",
    "Nautical_Twilight",
    "Astronomical_Twilight"
]
df = df.drop(columns=drop_cols)

In [26]:
# 9. Handle missing values in numeric columns
#    Fill numeric NaNs with median
num_cols = df.select_dtypes(include="number").columns.tolist()
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [27]:
# 10. Final clean-up: remove any remaining rows with NaNs
df = df.dropna()

In [28]:
# 11. stratify/drop rare severity classes if needed
# e.g., keep only severity levels 1-4
df = df[df["Severity"].isin([1,2,3,4])]

# Save cleaned dataset
df.to_csv("accidents_cleaned.csv", index=False)